### PR TITLE
Thread-safe message delivery in testing mode

### LINKED ISSUE #31: Testing mode is not thread safe
The message delivery in testing mode is not thread safe.

### PR DESCRIPTION
**Pull request by ashu210890**
Fixes #31

### CODE REVIEW

**Comment by ashu210890** [comment]
Tries the tests locally; they seem to be running fine.

**Comment by dasch** [comment]
There was an issue with the CI system – can you rebase on master?

**Comment by ashu210890** [comment]
Done, the tests are passing now.

**Comment by dasch** [comment]
Thanks!

**Pull request merged**
